DjangoUeditor/urls.py
# -*- coding: utf-8 -*-
import django
from .views import get_ueditor_controller

DJANGO_VERSION = django.VERSION[:2]


if DJANGO_VERSION >= (1, 8):
    try:
        from django.urls import re_path as url
    except ImportError:
        from django.conf.urls import url
    urlpatterns = [
        url(r'^controller/$', get_ueditor_controller)
    ]

else:
    try:
        from django.conf.urls import patterns, url
    except ImportError:
        from django.conf.urls.defaults import patterns, url

    urlpatterns = patterns('',
        url(r'^controller/$', get_ueditor_controller)
    )

EX3_89/urls.py
from django.conf import settings
from django.conf.urls.static import static
from homeApp89.views import home
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.urls import path
from django.urls import path, re_path
from django.views.generic.base import RedirectView
from django.conf import settings ##新增
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('aboutApp89/', include('aboutApp89.urls')),
    path('contactApp89/', include('contactApp89.urls')),
    path('homeApp89/', include('homeApp89.urls')),
    path('newsApp89/', include('newsApp89.urls')),
    path('productApp89/', include('productApp89.urls')),
    path('scienceApp89/', include('scienceApp89.urls')),
    path('serviceApp89/', include('serviceApp89.urls')),
    path('ueditor/', include('DjangoUeditor.urls')),
    path('search/', include('haystack.urls')),
    path('User/',include('User.urls')),
    re_path(r'^favicon.ico$', RedirectView.as_view(url=r'static/img/favicon.ico')),
    #url(r'^static/(?P<path>.*)$', static.serve, {'document_root': settings.STATIC_ROOT}, name='static'),
]

User/urls.py
from django.urls import path
from User.views import *
from . import views

app_name = 'User'

urlpatterns = [
        path("register/",views.register,name="register"),
        path("login/",views.login,name="login"),
]

contactApp89/urls.py
from django.urls import path
from . import views


app_name = 'contactApp89'

urlpatterns = [
    path("contact/", views.contact, name="contact"),
    path("recruit/", views.recruit, name="recruit"),
]

contactApp89/models.py
import os
from docxtpl import DocxTemplate
from docxtpl import InlineImage
from docx.shared import Mm, Inches, Pt
from django.core.mail import send_mail
from django.db.models.signals import post_init, post_save
from django.dispatch import receiver
from django.db import models
from django.utils import timezone
from datetime import datetime
# Create your models here.

class Ad(models.Model):
    title = models.CharField(max_length=50, verbose_name='招聘岗位')
    description = models.TextField(verbose_name='岗位要求')
    publishDate = models.DateTimeField(
        max_length=20, default=timezone.now, verbose_name='发布时间')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = '招聘广告'
        verbose_name_plural = '招聘广告'
        ordering = ('-publishDate',)

class Resume(models.Model):
    name = models.CharField(max_length=20, verbose_name='姓名',blank=True,
                                  null=True)
    experience = models.TextField(blank=True,
                                  null=True,
                                  verbose_name='学习或工作经历')
    photo = models.ImageField(upload_to='contact/recruit/%Y_%m_%d',
                              verbose_name='个人照片')
    grade_list = (
        (1, '未审'),
        (2, '通过'),
        (3, '未通过'),
    )
    status = models.IntegerField(choices=grade_list,
                                 default=1,
                                 verbose_name='面试成绩')
    publishDate = models.DateTimeField(max_length=20,
                                       default=timezone.now,
                                       verbose_name='提交时间')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '创意征集'
        verbose_name_plural = '创意征集'
        ordering = ('-status', '-publishDate')

@receiver(post_init, sender=Resume)
def before_save_resume(sender, instance, **kwargs):
    instance.__original_status = instance.status


@receiver(post_save, sender=Resume)
def post_save_resume(sender, instance, **kwargs):
    print(instance.__original_status)
    print(instance.status)


@receiver(post_save, sender=Resume)
def post_save_resume(sender, instance, **kwargs):
    email = instance.email                    # 应聘者邮箱
    EMAIL_FROM = '3315370938@qq.com'           # 企业QQ邮箱
    if instance.__original_status == 1 and instance.status == 2:
        email_title = '通知：恒达科技招聘初试结果'
        email_body = '恭喜您通过本企业初试'
        send_status = send_mail(email_title, email_body, EMAIL_FROM, [email])
    elif instance.__original_status == 1 and instance.status == 3:
        email_title = '通知：恒达科技招聘初试结果'
        email_body = '很遗憾，您未能通过本企业初试，感谢您的关注'
        send_status = send_mail(email_title, email_body, EMAIL_FROM, [email])

contactApp89/forms.py
from django import forms
from .models import Resume


class ResumeForm(forms.ModelForm):
    class Meta:
        model = Resume
        fields = ('name', 'experience', 'photo')
        widgets = {
            'photo': forms.FileInput(),
        }

contactApp89/views.py
from django.shortcuts import render
from .models import Ad
from .forms import ResumeForm
# Create your views here.


def contact(request):
    return render(request, 'contact.html', {'active_menu': 'contact', })


def recruit(request):
    AdList = Ad.objects.all().order_by('-publishDate')
    if request.method == 'POST':
        resumeForm = ResumeForm(data=request.POST, files=request.FILES)
        if resumeForm.is_valid():
            resumeForm.save()
            return render(request, 'success.html', {
                'active_menu': 'contacts',
                'sub_menu': 'recruit',
            })
    else:
        resumeForm = ResumeForm()
    return render(
        request, 'recruit.html', {
            'active_menu': 'contact',
            'sub_menu': 'recruit',
            'AdList': AdList,
            'resumeForm': resumeForm,
        })

contactApp89/templates/contact.html
{% extends "base.html" %} {% load static %}
<!--标题-->
{% block title %} 联系我们 {%endblock %}

<!--主体-->

{% block content %}

<!-- 广告横幅 -->
<link href="{% static "css/contact.css" %}" rel="stylesheet">
<div class="container-fluid">
  <div class="row">
    <img
      class="img-responsive model-img"
      src="{% static 'img/contact.jpg' %}"
    />
  </div>
</div>
<!-- 主体内容 -->
<div class="container">
  <div class="row row-3">
    <!-- 侧边导航栏 -->
    <div class="col-md-3">
      <div class="model-title">人才招聘</div>
      <div class="model-list">
        <ul class="list-group">
          <!--侧边栏部分采用Bootstrap提供的列表组件 list-group实现-->
          <li class="list-group-item" id="contact">
            <a href="{% url 'contactApp89:contact' %}">欢迎咨询</a>
          </li>
          <li class="list-group-item" id="recruit">
            <a href="{% url 'contactApp89:recruit' %}">加入我们</a>
          </li>
        </ul>
      </div>
    </div>
    <!-- 说明文字和图片 -->

    <div class="col-md-9">
      <div class="model-details-title">欢迎咨询</div>
      <div class="col-md-4">
        <div class="contact-left">
          <h1>
            <strong>伟大科技有限公司</strong>
            <span>weida Science and Technology</span>
          </h1>
          <ul>
            <li><span>业务质询一：</span>7895317155</li>
            <li><span>业务质询二：</span>9954743671</li>
            <li><span>咨询电话：</span>744611279378</li>
            <li><span>企业传真：</span>879856382001</li>
            <li><span>地址：</span>广州市花都区迎宾大道西30号</li>
            <li><span>邮编：</span>7446834</li>
            <li>
              <span>网址：</span>
              <a href="http://python3web.com">http://python3web.com</a>
            </li>
          </ul>
        </div>
      </div>
      <div class="col-md-8" style="margin-top: 20px">
        <!--百度地图容器-->
        <div
          style="width: 500px; height: 400px; border: #ccc solid 1px"
          id="dituContent"
        ></div>
      </div>
    </div>
  </div>
</div>

<style type="text/css">
  html,
  body {
    margin: 0;
    padding: 0;
  }
  .iw_poi_title {
    color: #cc5522;
    font-size: 14px;
    font-weight: bold;
    overflow: hidden;
    padding-right: 13px;
    white-space: nowrap;
  }
  .iw_poi_content {
    font: 12px arial, sans-serif;
    overflow: visible;
    padding-top: 4px;
    white-space: -moz-pre-wrap;
    word-wrap: break-word;
  }
</style>
<script
  type="text/javascript"
  src="http://api.map.baidu.com/api?key=&v=1.1&services=true"
></script>

<script type="text/javascript">
  //创建和初始化地图函数：
  function initMap() {
    createMap(); //创建地图
    setMapEvent(); //设置地图事件
    addMapControl(); //向地图添加控件
  }

  //创建地图函数：
  function createMap() {
    var map = new BMap.Map("dituContent"); //在百度地图容器中创建一个地图
    var point = new BMap.Point(113.191873, 23.411018); //定义一个中心点坐标
    map.centerAndZoom(point, 17); //设定地图的中心点和坐标并将地图显示在地图容器中
    window.map = map; //将map变量存储在全局
  }

  //地图事件设置函数：
  function setMapEvent() {
    map.enableDragging(); //启用地图拖拽事件，默认启用(可不写)
    map.enableScrollWheelZoom(); //启用地图滚轮放大缩小
    map.enableDoubleClickZoom(); //启用鼠标双击放大，默认启用(可不写)
    map.enableKeyboard(); //启用键盘上下左右键移动地图
  }

  //地图控件添加函数：
  function addMapControl() {
    //向地图中添加缩放控件
    var ctrl_nav = new BMap.NavigationControl({
      anchor: BMAP_ANCHOR_TOP_LEFT,
      type: BMAP_NAVIGATION_CONTROL_LARGE,
    });
    map.addControl(ctrl_nav);
    //向地图中添加缩略图控件
    var ctrl_ove = new BMap.OverviewMapControl({
      anchor: BMAP_ANCHOR_BOTTOM_RIGHT,
      isOpen: 1,
    });
    map.addControl(ctrl_ove);
    //向地图中添加比例尺控件
    var ctrl_sca = new BMap.ScaleControl({ anchor: BMAP_ANCHOR_BOTTOM_LEFT });
    map.addControl(ctrl_sca);
  }

  initMap(); //创建和初始化地图
</script>
{% endblock %}

contactApp89/templates/recruit.html
{% extends "base.html" %} {% load static %}{% load widget_tweaks %}
<!--标题-->
{% block title %} 加入我们 {%endblock %}

<!--主体-->

{% block content %} <link href="{% static "css/contact.css" %}"
rel="stylesheet">
{% comment %}
<div class="container-fluid">
  <div class="row">
    <img
      class="img-responsive model-img"
      src="{% static 'img/contact.jpg' %}"
    />
  </div>
</div>
{% endcomment %}
<!-- 主体内容 -->
<div class="container">
	{% comment %}
  <div class="row row-3">
    <!-- 侧边导航栏 -->
    <div class="col-md-3">
      <div class="model-title">人才招聘</div>
      <div class="model-list">
        <ul class="list-group">
          <!--侧边栏部分采用Bootstrap提供的列表组件 list-group实现-->
          <li class="list-group-item" id="contact">
            <a href="{% url 'contactApp89:contact' %}">欢迎咨询</a>
          </li>
          <li class="list-group-item" id="recruit">
            <a href="{% url 'contactApp89:recruit' %}">加入我们</a>
          </li>
        </ul>
      </div>
    </div>
    {% endcomment %}
    <!-- 说明文字和图片 -->

    <div class="col-md-12">
      <div class="model-details-title">欢迎投稿</div>
      <div class="model-details">
    <div class="panel-group" id="accordion">
    {% for ad in AdList %}
    <div class="panel panel-default">
        <div class="panel-heading" role="tab" id="panel{{ad.id}}">
            <h4 class="panel-title">
                {% if forloop.first %}
                <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapse{{ad.id}}">
                {% else %}
                <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapse{{ad.id}}">
                {% endif %}
                    {{ad.title}}
            </a>
            </h4>
        </div>
        {% if forloop.first %}
        <div id="collapse{{ad.id}}" class="panel-collapse collapse in">
        {% else %}
        <div id="collapse{{ad.id}}" class="panel-collapse collapse">
        {% endif %}
                <div class="panel-body">
                    <p>{{ad.description}}</p>
                </div>
        </div>
    </div>
    {% endfor %}
    </div>
    </div>
<div class="panel panel-default">
                <div class="panel-heading">
                    请填写道具描述
                </div>
                <div class="panel-body">
                    <div class="row">
                        <form action="." name="resumeForm" class="form-horizontal" method="post" role="form" enctype="multipart/form-data">
                            {% csrf_token %}
                            <!-- 左侧 -->
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="col-sm-3 control-label">道具名称：</label>
                                    <div class="col-sm-9">
                                        {{resumeForm.name|add_class:"form-control"|attr:"placeholder=请填写道具名"}}
                                    </div>
                                </div>
				<div class="form-group">
                                    <label class="col-sm-5 control-label">道具用途及创作思想：</label>
                                    <div class="col-sm-12">
                                        {{resumeForm.experience|add_class:"form-control"}}
                                    </div>
                                </div>

                            </div>
                            <!-- 右侧 -->
			    <div class="col-md-6">
                                <div class="form-group">
                                    <div class="col-sm-12" style="text-align:center">
                                        <img id="profileshow" style="width:120px" src="{% static 'img/sample.png' %}">
                                    </div>
                                    <label class="col-sm-5 control-label">上传道具概念图：</label>
                                    {{resumeForm.photo}}
                                </div>
			    </div>
                            <div class="col-md-12">
                                <center><input type="submit" class="btn btn-primary" value="提交" /></center>
                            </div>
                        </form>
                    </div>
                </div>
            </div>   
    </div>
  </div>
</div>

<script src="{% static 'js/laydate.js' %}"></script>

<script>
    laydate.render({
        elem: '#id_birth'
    });
</script>


<script>
    $(function () {
        $('#id_photo').on('change', function () {
            var r = new FileReader();
            f = document.getElementById('id_photo').files[0];
            r.readAsDataURL(f);
            r.onload = function (e) {
                document.getElementById('profileshow').src = this.result;
            };
        });
    });
</script>
{% endblock %}

contactApp89/templates/success.html
{% extends "base.html" %} {% load static %}
<!--  -->
{% block title %} 人才招聘 {% endblock %}
<!---->
{% block content %}
<!-- 主体内容 -->
<div class="container">
  <div class="row">
    <div class="alert alert-success">
      <strong>成功!</strong> 道具信息已成功上传，结果会以邮件方式发给您。
    </div>
  </div>
</div>
{% endblock %}