DjangoUeditor/urls.py
# -*- coding: utf-8 -*-
import django
from .views import get_ueditor_controller

DJANGO_VERSION = django.VERSION[:2]


if DJANGO_VERSION >= (1, 8):
    try:
        from django.urls import re_path as url
    except ImportError:
        from django.conf.urls import url
    urlpatterns = [
        url(r'^controller/$', get_ueditor_controller)
    ]

else:
    try:
        from django.conf.urls import patterns, url
    except ImportError:
        from django.conf.urls.defaults import patterns, url

    urlpatterns = patterns('',
        url(r'^controller/$', get_ueditor_controller)
    )

EX3_89/urls.py
from django.conf import settings
from django.conf.urls.static import static
from homeApp89.views import home
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.urls import path
from django.urls import path, re_path
from django.views.generic.base import RedirectView
from django.conf import settings ##新增
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('aboutApp89/', include('aboutApp89.urls')),
    path('contactApp89/', include('contactApp89.urls')),
    path('homeApp89/', include('homeApp89.urls')),
    path('newsApp89/', include('newsApp89.urls')),
    path('productApp89/', include('productApp89.urls')),
    path('scienceApp89/', include('scienceApp89.urls')),
    path('serviceApp89/', include('serviceApp89.urls')),
    path('ueditor/', include('DjangoUeditor.urls')),
    path('search/', include('haystack.urls')),
    path('User/',include('User.urls')),
    re_path(r'^favicon.ico$', RedirectView.as_view(url=r'static/img/favicon.ico')),
    #url(r'^static/(?P<path>.*)$', static.serve, {'document_root': settings.STATIC_ROOT}, name='static'),
]

User/urls.py
from django.urls import path
from User.views import *
from . import views

app_name = 'User'

urlpatterns = [
        path("register/",views.register,name="register"),
        path("login/",views.login,name="login"),
]

aboutApp89/urls.py

from django.urls import path
from . import views

app_name = 'aboutApp89'

urlpatterns = [
    path('survey/', views.survey, name='survey'),
    path('honor/', views.honor, name='honor'),
]

contactApp89/urls.py
from django.urls import path
from . import views


app_name = 'contactApp89'

urlpatterns = [
    path("contact/", views.contact, name="contact"),
    path("recruit/", views.recruit, name="recruit"),
]

homeApp89/urls.py
from django.urls import path
from . import views

app_name = 'homeApp89'
urlpatterns = [
    path("home/", views.home, name="home"),
]

newsApp89/urls.py
from django.urls import path
from . import views

app_name = 'newsApp89'

urlpatterns = [
    path('news/<str:newName>/', views.news, name='news'),
    path('newDetail/<int:id>/', views.newDetail, name='newDetail'),
    path('search/', views.search, name='search'),
]

productApp89/urls.py
from django.urls import path
from . import views

app_name = 'productApp89'

urlpatterns = [
    path('products/<str:productName>/', views.products, name='products'),  # 产品列表
    path('productDetail/<int:id>/', views.productDetail,
         name='productDetail'),  # 产品详情
]

homeApp89/models.py
from django.db import models

# Create your models here.

homeApp89/views.py
from django.shortcuts import render
from productApp89.models import Product
from productApp89.models import ProductImg
from django.shortcuts import HttpResponse


# def home(request):
#     return render(request, 'home.html', {'active_menu': 'home', })

from newsApp89.models import MyNew
from django.db.models import Q  # 用于对象的复杂查询，可以对关键字参数进行封装，从而更好地应用于多条件查询


def home(request):
    # 新闻展报
    newList = MyNew.objects.all().filter(~Q(
        newType='通知公告')).order_by('-publishDate')
    postList = set()
    postNum = 0
    for s in newList:
        if s.photo:
            postList.add(s)
            postNum += 1
        if postNum == 3:
            break

    # 通知公告
    noteList = MyNew.objects.all().filter(
        Q(newType='通知公告')).order_by('-publishDate')
    if (len(noteList) > 4):
        noteList = noteList[0:4]

    productList = Product.objects.all().order_by('-views')
    if (len(productList) > 4):
        productList = productList[0:4]

    # 新闻列表
    if (len(newList) > 7):
        newList = newList[0:7]

    return render(request, 'home.html', {
        "active_menu": "home",
        "postList": postList,
        "newList": newList,
        "productList": productList,
    })

homeApp89/templates/home.html
{% extends "base.html" %} {% load static %}
<!--标题-->
{% block title %} 首页 {% endblock %}
<!--主体-->
{% block content %}
<link href="{% static 'css/home.css' %}" rel="stylesheet" />
<script src="{% static 'js/jqthumb.min.js' %}"></script>
{% comment %}
<div id="ad" class="carousel slide" data-ride="carousel" data-interval="5000">
  <ol class="carousel-indicators">
    <!--绑定轮播索引-->
    <li data-target="#ad" data-slide-to="0" class="active"></li>
    <!--data-slide-to设置每张图片的轮播标号-->
    <li data-target="#ad" data-slide-to="1"></li>
    <li data-target="#ad" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <!--carousel-inner实现每张图像的内容显示-->
    <div class="item active">
      <img src="{% static 'img/banner1.jpg' %}" alt="广告横幅1" />
    </div>
    <div class="item">
      <img src="{% static 'img/banner2.jpg' %}" alt="广告横幅2" />
    </div>
    <div class="item">
      <img src="{% static 'img/banner3.jpg' %}" alt="广告横幅3" />
    </div>
  </div>
  <!--left carousel-control用于控制左右侧的图片切换功能-->
  <a class="left carousel-control" href="#ad" data-slide="prev"
    ><span class="glyphicon glyphicon-chevron-left"></span
  ></a>
  <a class="right carousel-control" href="#ad" data-slide="next"
    ><span class="glyphicon glyphicon-chevron-right"></span
  ></a>
</div>
{% endcomment %}
<!--下部主体部分-->
<div class="container">
  <div class="row row-3">
    <div class="col-md-4">
      <!-- 哆啦百科 -->
      <span class="part1">
	      <a href="{% url 'aboutApp89:survey' %}">哆啦百科</a>
      </span>
      <div class="line1">
        <div class="line2 theme"></div>
      </div>
      <div>
        <img class="img-responsive img-rounded" src="{% static 'img/th.jpg' %}" />
        <p class="text1">
          《哆啦A梦》（日语：ドラえもん，英语：Doraemon，香港译作“多啦A梦”）为日本漫画家藤子·F·不二雄笔下的儿童、科幻类型日本漫画，自1969年12月[注 4]开始连载[1][2]，共发行单行本45册
        </p>
      </div>
    </div>
    <div class="col-md-8">
      <!-- 新番速递 -->
      <span class="part1">
                <a href="{% url 'newsApp89:news' 'company' %}">新番速递</a>
            </span>
            <a class="btn btn-default btn-xs more-btn" href="{% url 'newsApp89:news' 'company' %}">+&nbsp;更多</a>
            <div class="line1">
                <div class="line2 theme"></div>
            </div>
            <div class="col-md-5">
                <div id="myCarousel" class="carousel slide" data-ride="carousel">
                    <ol class="carousel-indicators nav-point">
                        {% for post in postList %}
                        <li data-target="#myCarousel" data-slide-to="{{forloop.counter0}}" {% if forloop.first %} class="active" {% endif %}>
                        </li>
                        {% endfor %}
                    </ol>
                    <!-- 轮播（Carousel）项目 -->
                    <div class="carousel-inner">
                        {% for post in postList %}
                        <div {% if forloop.first %} class="item active" {% else %} class="item" {% endif %} style="background-size:cover;">
                            <a href="{% url 'newsApp89:newDetail' post.id %}">
                                <img src="{{post.photo.url}}" class="img-responsive" onload="DrawImage(this)">
                            <div class="carousel-caption nav-title">{{post.title}}</div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
            <div class="col-md-7">
                <ul class="list-unstyled list-new">
                    {% for mynew in newList %}
                    <li>
                        <a href="{% url 'newsApp89:newDetail' mynew.id %}">
                            {{mynew.title|truncatechars:"25"}}</a>
                        <span>【{{mynew.publishDate|date:"Y-m-d"}}】</span>
                    </li>
                    {% endfor %}
                </ul>
            </div>
    </div>
  </div>
  <div class="row row-3">
{% comment %}
    <div class="col-md-4">
      <!-- 通知公告 -->
      <span class="part1">
                <a href="#">通知公告</a>
            </span>
            <span class="part1 en">
                &nbsp;&nbsp;/ Public Release
            </span>
            <a class="btn btn-default btn-xs more-btn" href="{% url 'newsApp89:news' 'notice' %}">+&nbsp;更多</a>
            <div class="line1">
                <div class="line2 theme"></div>
            </div>
            <div>
                <img class="img-responsive" src="{% static 'img/note.jpg' %}">
                <ul class="list-unstyled list-new">
                    {% for note in noteList %}
                    <li>
                        <a href="{% url 'newsApp89:newDetail' note.id %}">
                            {{note.title|truncatechars:"25"}}
                        </a>
                        <a href="{% url 'newsApp89:newDetail' note.id %}" class="public-detail">
                            查看详情>>
                        </a>
                    </li>
                    {% endfor %}
                </ul>
            </div>
    </div>
{% endcomment %}
    <div class="col-md-6">
      <!-- 壁纸下载 -->
      <span class="part1">
                <a href="{% url 'serviceApp89:download'%}">壁纸下载</a>
      </span>
        <div class="line1">
            <div class="line2 theme"></div>
        </div>
        <div>
            <a href="{% url 'serviceApp89:download' %}"><img class="img-responsive img-rounded" src="{% static 'img/th2.jpg' %}"></a>
            <p class="text1">
                <font color="#d30a1c"></font>
                    
            </p>
        </div>
    </div>
    <div class="col-md-6">
      <!-- 创意道具征集  -->
      <span class="part1">
                <a href="{% url 'contactApp89:recruit' %}">创意道具征集</a>
            </span>
            <div class="line1">
                <div class="line2 theme"></div>
            </div>
            <div>
                <ul class="list-unstyled procurement-li">
                    <li>业务质询一：66666666</li>
                    <li>业务质询二：88888888</li>
                    <li>咨询电话：114514</li>
                    <li>企业传真：1919890</li>
                    <li>地址：东京都港区三田</li>
                    <li>邮编：doraemon@dora.com</li>
                    <li>
                        网址：<a href="https://www.dora-family.com/">https://www.dora-family.com/</a>
                    </li>
                </ul>
                <div class="platform"><a href="{% url 'contactApp89:recruit' %}">详情</a></div>
            </div>
    </div>
  </div>
  <div class="row row-3">
    <!-- 哆啦百宝袋 -->
    <div class="col-md-12 col-pro">
        <div class="row">
            <div class="col-md-12">
                <span class="part1">
                    <a href="{% url 'productApp89:products' 'dora' %}">哆啦百宝袋</a>
                </span>
                    <a class="btn btn-default btn-xs more-btn" href="{% url 'productApp89:products' 'robot' %}">+&nbsp;更多</a>
            <div class="line1" style="margin-bottom:5px;">
                <div class="line2 theme"></div>
        </div>
    </div>
    <div class="col-md-12 col-pro">
        <div id="Carousel" class="carousel slide" style="margin-bottom:30px">
            <ol class="carousel-indicators" style="display:none;">
                <li data-target="#Carousel" data-slide-to="0" class="active"></li>
            </ol>
            <div class="carousel-inner">
                <div class="item active">
                    <div class="row">
                        {% for product in productList %}
                            <div class="col-md-3 pro-images">
                                <a href="{% url 'productApp89:productDetail' product.id %}" class="thumbnail">
                                    {% for img in product.productImgs.all %}
                                    {% if forloop.first %}
                                    <img src="{{img.photo.url}}" alt="产品图片" class="img-responsive" onload="DrawImage(this)">
                                    {% endif %}
                                    {% endfor %}
                                </a>
                                <div class="carousel-caption nav-title">{{product.title}}</div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
  </div>
	</div>
  </div>

</div> 

<script>
    //处理缩略图
    function DrawImage(hotimg) {
        $(hotimg).jqthumb({
            width: '100%', // 宽度
            height: '220px', // 高度
            zoom: '1', // 缩放比例
            method: 'auto' // 提交方法，用于不同的浏览器环境，默认为‘auto’
        });
    }
</script>
{% endblock %}