DjangoUeditor/urls.py
# -*- coding: utf-8 -*-
import django
from .views import get_ueditor_controller

DJANGO_VERSION = django.VERSION[:2]


if DJANGO_VERSION >= (1, 8):
    try:
        from django.urls import re_path as url
    except ImportError:
        from django.conf.urls import url
    urlpatterns = [
        url(r'^controller/$', get_ueditor_controller)
    ]

else:
    try:
        from django.conf.urls import patterns, url
    except ImportError:
        from django.conf.urls.defaults import patterns, url

    urlpatterns = patterns('',
        url(r'^controller/$', get_ueditor_controller)
    )

EX3_89/urls.py
from django.conf import settings
from django.conf.urls.static import static
from homeApp89.views import home
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.urls import path
from django.urls import path, re_path
from django.views.generic.base import RedirectView
from django.conf import settings ##新增
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('aboutApp89/', include('aboutApp89.urls')),
    path('contactApp89/', include('contactApp89.urls')),
    path('homeApp89/', include('homeApp89.urls')),
    path('newsApp89/', include('newsApp89.urls')),
    path('productApp89/', include('productApp89.urls')),
    path('scienceApp89/', include('scienceApp89.urls')),
    path('serviceApp89/', include('serviceApp89.urls')),
    path('ueditor/', include('DjangoUeditor.urls')),
    path('search/', include('haystack.urls')),
    path('User/',include('User.urls')),
    re_path(r'^favicon.ico$', RedirectView.as_view(url=r'static/img/favicon.ico')),
    #url(r'^static/(?P<path>.*)$', static.serve, {'document_root': settings.STATIC_ROOT}, name='static'),
]

User/urls.py
from django.urls import path
from User.views import *
from . import views

app_name = 'User'

urlpatterns = [
        path("register/",views.register,name="register"),
        path("login/",views.login,name="login"),
]

serviceApp89/urls.py
from django.urls import path
from . import views
app_name = 'serviceApp89'

urlpatterns = [
    path("download/", views.download, name="download"),
    path("platform/", views.platform, name="platform"),
    path('getDoc/<int:id>/', views.getDoc, name='getDoc'),
]

serviceApp89/models.py
from django.db import models

import django.utils.timezone as timezone
# Create your models here.


class Doc(models.Model):
    title = models.CharField(max_length=250, verbose_name='壁纸名称')
    file = models.FileField(upload_to='Service/',
                            blank=True,
                            verbose_name='上传壁纸')
    publishDate = models.DateTimeField(max_length=20,
                                       default=timezone.now,
                                       verbose_name='发布时间')

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-publishDate']
        verbose_name = "壁纸"
        verbose_name_plural = verbose_name


class DocImg(models.Model):
    doc = models.ForeignKey(Doc,
                                related_name='docImgs',
                                verbose_name='壁纸',
                                on_delete=models.CASCADE)
    photo = models.ImageField(upload_to='Doc/',
                              blank=True,
                              verbose_name='壁纸预览图')
    class Meta:
        verbose_name = '壁纸'
        verbose_name_plural = '壁纸'

serviceApp89/views.py
from django.shortcuts import get_object_or_404
import os
from django.http import StreamingHttpResponse
from django.shortcuts import render

# def platform(request):
#     return render(request, 'platform.html', {'active_menu': 'platform'})


# def download(request):
#     return render(request, 'docList.html', {'active_menu': 'docList'})

from django.shortcuts import render
from django.shortcuts import HttpResponse
from .models import Doc
from django.core.paginator import Paginator

from django.shortcuts import get_object_or_404
from django.http import StreamingHttpResponse
import os


def read_file(file_name, size):
    with open(file_name, mode='rb') as fp:
        while True:
            c = fp.read(size)
            if c:
                yield c
            else:
                break


def getDoc(request, id):
    doc = get_object_or_404(Doc, id=id)
    update_to, filename = str(doc.file).split('/')
    filepath = '%s/media/%s/%s' % (os.getcwd(), update_to, filename)
    response = StreamingHttpResponse(read_file(filepath, 512))
    response['Content-Type'] = 'application/octet-stream'
    response['Content-Disposition'] = 'attachment;filename="{}"'.format(filename)
    return response


def download(request):
    # 从数据库获取、过滤和排序数据
    docList = Doc.objects.all().order_by('-publishDate')
    # 分页
    p = Paginator(docList, 5)
    if p.num_pages <= 1:
        pageData = ''
    else:
        page = int(request.GET.get('page', 1))
        newList = p.page(page)
        left = []
        right = []
        left_has_more = False
        right_has_more = False
        first = False
        last = False
        total_pages = p.num_pages
        page_range = p.page_range
        if page == 1:
            right = page_range[page:page + 2]
            print(total_pages)
            if right[-1] < total_pages - 1:
                right_has_more = True
            if right[-1] < total_pages:
                last = True
        elif page == total_pages:
            left = page_range[(page - 3) if (page - 3) > 0 else 0:page - 1]
            if left[0] > 2:
                left_has_more = True
            if left[0] > 1:
                first = True
        else:
            left = page_range[(page - 3) if (page - 3) > 0 else 0:page - 1]
            right = page_range[page:page + 2]
            if left[0] > 2:
                left_has_more = True
            if left[0] > 1:
                first = True
            if right[-1] < total_pages - 1:
                right_has_more = True
            if right[-1] < total_pages:
                last = True
        pageData = {
            'left': left,
            'right': right,
            'left_has_more': left_has_more,
            'right_has_more': right_has_more,
            'first': first,
            'last': last,
            'total_pages': total_pages,
            'page': page,
        }
    return render(
        request, 'docList.html', {
            'newName': '壁纸下载',
            'active_menu': 'service',
            'sub_menu': 'download',
            'docList': docList,
            'pageData': pageData,
        })


def platform(request):
    return render(
        request, 'platform.html', {
            'newName': '人工智能开放平台',
            'active_menu': 'service',
            'sub_menu': 'platform',
        })

serviceApp89/templates/docList.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    {{ newName }}
{% endblock %}

{% block content %}

<link href="{% static 'css/service.css' %}" rel="stylesheet">  
    <!-- 主体内容 -->
<div class="container">
        <div class="row row-3">
            
                <div class="model-details-title">
                    {{ newName }}
                </div>
                <div class="box">
                    {% for doc in docList %}
			   <div class=""> 
			    {% for img in doc.docImgs.all %}
           			 {% if forloop.first %}
				 <a href="#">
                			<img class="img-responsive model-img" src="{{img.photo.url}}">
           			 </a>
           			 {% endif %}
       			     {% endfor %}
                            <a href="{% url 'serviceApp89:getDoc' doc.id %}"><b class="caption1">{{ doc.title }}</b></a>
			    <!--    <span>【{{ doc.publishDate|date:"Y-m-d" }}】</span>  -->
			   </div>
			   
                    {% endfor %}   
              </div>
      	<div>
	       
        <div class="paging">
  <ul id="pages" class="pagination pagination-sm pagination-xs">
    {% if pageData.first %}
      <li><a href="?page=1">1</a></li>
    {% endif %}
    {% if pageData.left_has_more %}
      <li><span>...</span></li>
    {% endif %}
    {% for i in pageData.left %}
      <li><a href="?page={{ i }}">{{ i }}</a></li>
    {% endfor %}
    <li class="active"><a href="?page={{ pageData.page }}">{{ pageData.page }}</a></li>
    {% for i in pageData.right %}
      <li><a href="?page={{ i }}">{{ i }}</a></li>
    {% endfor %}
    {% if pageData.right_has_more %}
      <li><span>...</span></li>
    {% endif %}
    {% if pageData.last %}
      <li><a href="?page={{ pageData.total_pages }}">{{ pageData.total_pages }}</a></li>
    {% endif %}
  </ul>
</div>

        
        </div>
  </div>
</div>

{% endblock %}