DjangoUeditor/urls.py
# -*- coding: utf-8 -*-
import django
from .views import get_ueditor_controller

DJANGO_VERSION = django.VERSION[:2]


if DJANGO_VERSION >= (1, 8):
    try:
        from django.urls import re_path as url
    except ImportError:
        from django.conf.urls import url
    urlpatterns = [
        url(r'^controller/$', get_ueditor_controller)
    ]

else:
    try:
        from django.conf.urls import patterns, url
    except ImportError:
        from django.conf.urls.defaults import patterns, url

    urlpatterns = patterns('',
        url(r'^controller/$', get_ueditor_controller)
    )

EX3_89/urls.py
from django.conf import settings
from django.conf.urls.static import static
from homeApp89.views import home
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.urls import path
from django.urls import path, re_path
from django.views.generic.base import RedirectView
from django.conf import settings ##新增
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('aboutApp89/', include('aboutApp89.urls')),
    path('contactApp89/', include('contactApp89.urls')),
    path('homeApp89/', include('homeApp89.urls')),
    path('newsApp89/', include('newsApp89.urls')),
    path('productApp89/', include('productApp89.urls')),
    path('scienceApp89/', include('scienceApp89.urls')),
    path('serviceApp89/', include('serviceApp89.urls')),
    path('ueditor/', include('DjangoUeditor.urls')),
    path('search/', include('haystack.urls')),
    path('User/',include('User.urls')),
    re_path(r'^favicon.ico$', RedirectView.as_view(url=r'static/img/favicon.ico')),
    #url(r'^static/(?P<path>.*)$', static.serve, {'document_root': settings.STATIC_ROOT}, name='static'),
]

User/urls.py
from django.urls import path
from User.views import *
from . import views

app_name = 'User'

urlpatterns = [
        path("register/",views.register,name="register"),
        path("login/",views.login,name="login"),
]

aboutApp89/urls.py

from django.urls import path
from . import views

app_name = 'aboutApp89'

urlpatterns = [
    path('survey/', views.survey, name='survey'),
    path('honor/', views.honor, name='honor'),
]

contactApp89/urls.py
from django.urls import path
from . import views


app_name = 'contactApp89'

urlpatterns = [
    path("contact/", views.contact, name="contact"),
    path("recruit/", views.recruit, name="recruit"),
]

newsApp89/urls.py
from django.urls import path
from . import views

app_name = 'newsApp89'

urlpatterns = [
    path('news/<str:newName>/', views.news, name='news'),
    path('newDetail/<int:id>/', views.newDetail, name='newDetail'),
    path('search/', views.search, name='search'),
]

productApp89/urls.py
from django.urls import path
from . import views

app_name = 'productApp89'

urlpatterns = [
    path('products/<str:productName>/', views.products, name='products'),  # 产品列表
    path('productDetail/<int:id>/', views.productDetail,
         name='productDetail'),  # 产品详情
]

templates/base.html
<!DOCTYPE html>

<html>
  <head>
    {% load static %}
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=EDGE" />
    <title>哆啦之家|{% block title%}{% endblock%}</title>
    <link href="{%static 'css/bootstrap.css'%}" rel="stylesheet" />
    <link href="{% static 'css/style.css' %}" rel="stylesheet" />
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <link rel="shortcut icon" href="{%static "img/favicon.ico" %}" />
  </head>
  <body>
{% comment %}	  
    <div class="container top">
      <div class="row">
        <div class="col-md-6">
          <a><img class="img-responsive" src="{% static 'img/logo.jpg'%}" /></a>
        </div>
        <div class="col-md-3 hidden-xs">
          <a class="phone ant">
            <span class="glyphicon glyphicon-phone"></span>学号:21551117089
            &nbsp;&nbsp;
          </a>
        </div>
        <div class="col-md-3 hidden-xs">
          <a class="mail ant">
            <span class="glyphicon glyphicon-envelope"></span
            >E-mail:LJF89-123456@163.com
          </a>
        </div>
      </div>
    </div>
   {% endcomment %}
    <nav class="navbar navbar-default" role="navigation">
      <div class="container">
          <ul class="nav navbar-nav active" style="width: 100%">
            <li class="nav-top" id="home">
              <a href="{% url 'home'%}">首页</a>
            </li>
            <li class="nav-top" id="about">
              <a href="{% url 'aboutApp89:survey' %}">哆啦百科</a>
            </li>
            <li class="nav-top" id="news">
              <a href="{% url 'newsApp89:news' 'company'%}"  >新番速递</a> 
            </li>
            <li class="nav-top" id="products">
              <a href="{% url 'productApp89:products' 'dora' %}">百宝袋</a>
	      {% comment %}
              <ul class="dropdown-menu">
                <li>
                  <a href="{% url 'productApp89:products' 'robot' %}"
                    >家用机器人</a
                  >
                </li>
                <li>
                  <a href="{% url 'productApp89:products' 'monitor' %}"
                    >智能监控</a
                  >
                </li>
                <li>
                  <a href="{% url 'productApp89:products' 'face' %}"
                    >人脸识别解决方案</a
                  >
                </li>
              </ul>
	      {% endcomment %}
            </li>
            <li class="nav-top" id="service">
              <a href="{% url 'serviceApp89:download' %}">壁纸下载</a>
            </li>
            <li class="nav-top" id="contact">
              <a href="{% url 'contactApp89:recruit' %}">创意征集</a>
            </li>
	    <li class="nav-top" id="">
              <a href="{% url 'User:login' %}">登录</a>
            </li>
          </ul>
        
      </div>
    </nav>

    <div class="line"></div>

    {% block content %} {% endblock %}

{% comment %}  <div class="container web-footer">
      <!--map-->
      <div class="row" id="map-footer">
        <div class="col-md-2" id="honor">
          <dl>
            <dt>公司简介</dt>
            <dd><a href="{% url 'aboutApp89:survey'%}">企业概况</a></dd>
            <dd><a href="{% url 'aboutApp89:honor'%}">荣誉资质</a></dd>
          </dl>
        </div>

        <div class="col-md-2">
          <dl>
            <dt>产品中心</dt>
            <dd>
              <a href="{% url 'productApp89:products' 'robot' %}"
                >家用智能机器人</a
              >
            </dd>
            <dd>
              <a href="{% url 'productApp89:products' 'monitor' %}">智能监控</a>
            </dd>
            <dd>
              <a href="{% url 'productApp89:products' 'face' %}">人脸识别</a>
            </dd>
          </dl>
        </div>
        <div class="col-md-2">
          <dl>
            <dt>服务支持</dt>
            <dd><a href="{% url 'serviceApp89:download'%}">资料下载</a></dd>
            <dd>
              <a href="{% url 'serviceApp89:platform'%}">人脸识别开放平台</a>
            </dd>
          </dl>
        </div>
        <div class="col-md-2">
      <!--版权-->
      <div class="row" id="patent-footer">
        <p>@2023 Python Web 梁俊枫 版权无有</p>
      </div>
    </div>
{% endcomment %}
    <script type="text/JavaScript">
      //dango变量注释它也是读的出来的,是django变量,可以在应用文件夹下的views.py中设置对应变量，一般用字典表示
          $('#scienceApp89').addClass("active"); //是为了添加激活属性到#{{active_menu}}该标签中
    </script>

    <script type="text/JavaScript">
      $('#aboutApp89').addClass("active");
    </script>

    <script type="text/JavaScript">
      //dango变量注释它也是读的出来的,是django变量,可以在应用文件夹下的views.py中设置对应变量，一般用字典表示
          $('#{{active_menu}}').addClass("active");
          $('#{{active_menu1}}').addClass("active");
    </script>

    <script>
      $(function () {
        $(".dropdown").mouseover(function () {
          $(this).addClass("open");
        });
        $(".dropdown").mouseleave(function () {
          $(this).removeClass("open");
        });
      });
    </script>

    <script>
      $("#{{sub_menu}}").addClass("active");
    </script>
  </body>
</html>